version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:

      - echo Installing dependencies...
      - npm install 
  build:
    commands:
      - echo Build completed successfully.
artifacts:
  files:
    - '**/*'