---
apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: todo-app
  name: my-todo-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-app-container
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: todo-app-container
    spec:
      containers:
      - image: haroonniamat029/knight-space:${BUILD_NUMBER}
        imagePullPolicy: Always
        name: todo-app-container
        ports:
        - containerPort: 80
          protocol: TCP
      
---
apiVersion: v1
kind: Service
metadata:
  namespace: todo-app
  name: todo-app-service
  labels:
    name: todo-app-service
    app: my-todo-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: todo-app-service
    app:  my-todo-app
