pipeline {
    
    agent any
    environment{
        SONAR_HOME = tool "SonarScanner"
    }
    stages {
        
        stage("Code"){
            steps{
                git url: "https://github.com/chaitraliawasare/node-todo-cicd.git" , branch: "master"
                echo "Code Cloned Successfully"
            }
        }
        
        stage("Test"){
            steps{
                withSonarQubeEnv("Sonar"){
                    sh "$SONAR_HOME/bin/sonar-scanner -Dsonar.projectName=nodetodo -Dsonar.projectKey=nodetodo"
                }
            }
        }
        stage("SonarQube Quality Test"){
            steps{
                timeout(time: 1,unit: "MINUTES"){
                    waitForQualityGate abortPipeline: false
                }
            }
        }
        stage("Build"){
            steps{
                sh 'docker build -t jenkinsproject:latest .'
                echo "Code Built Successfully"
            }
        }
        stage("Push to Private Docker Hub Repo"){
            steps{
                withCredentials([usernamePassword(credentialsId:"docker-creds",passwordVariable:"dockerPass",usernameVariable:"dockerUser")]){
                sh "docker login -u ${env.dockerUser} -p ${env.dockerPass}"
                sh "docker tag jenkinsproject:latest ${env.dockerUser}/jenkinsproject:latest"
                sh "docker push ${env.dockerUser}/jenkinsproject:latest"
                }
                
            }
        }
        
        stage("OWASP"){
            steps{
                dependencyCheck additionalArguments: '--scan ./', odcInstallation: 'OWASP'
                dependencyCheckPublisher pattern: '**/dependency-check-report.xml'
            }
        }
        stage("Trivy"){
            steps{
                sh "trivy image jenkinsproject:latest"
            }
        }
        stage("Deploy"){
            steps{
                sh "docker-compose up -d"
                echo "App Deployed Successfully"
            }
        }
    }
}
