name: Build and Push Docker Image to Dockerhub

on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t "${DOCKERHUB_USERNAME}"/node-todo:latest .
      - name: Login to DockerHub
        run: echo "${DOCKERHUB_TOKEN}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin
      - name: Push Docker Image to DockerHub
        run: docker push "${DOCKERHUB_USERNAME}"/node-todo:latest
